### ISSUE TITLE
Signing in with stored credentials now produces this error

### ISSUE THREAD

**Issue by Davidi74** [makiprogrammer/ts-messenger-api#16]
Hi,

It appears something has changed and now getting this error.

It seems to work when signing in using username/password

Error: Cookie not in this host's domain. Cookie:www.facebook.com Request:www.messenger.com
    at CookieJar.setCookie (C:\fb\node_modules\tough-cookie\lib\cookie.js:1133:15)
    at CookieJar.setCookie (C:\fb\node_modules\universalify\index.js:5:67)
    at CookieJar.setCookieSync (C:\fb\node_modules\tough-cookie\lib\cookie.js:1642:17)
    at Jar.setCookie (C:\fb\node_modules\ts-messenger-api\dist\lib\jar.js:9:26)
    at C:\fb\node_modules\ts-messenger-api\dist\lib\utils.js:572:17
    at Array.forEach (<anonymous>)
    at C:\fb\node_modules\ts-messenger-api\dist\lib\utils.js:567:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by thvozdovic** [comment]
Same issue here, @makiprogrammer is this project still maintained?

**Comment by lv185039** [comment]
This issue is due to the way cookies are handled and written to the appstate.  I have fixed this in my own internal fork of this repo, I will look over this repo and see if I can suggest a fix for it.
